const products = [
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    gender: "Kids",
    publish: "draft",
    category: "Accessories",
    available: 10,
    priceSale: 83.74,
    taxes: 10,
    quantity: 80,
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    inventoryType: "in stock",
    images: [
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_2.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_3.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_4.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_5.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_6.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_7.jpg",
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_8.jpg",
    ],

    tags: ["Technology", "Marketing", "Design", "Photography", "Art"],
    code: "38BEE270",
    description:
      "\n<h6>Specifications</h6>\n<br/>\n<ol>\n  <li>Category</li>\n  <li>Shoes</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Manufacturer</li>\n  <li>Nike</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Serial Number</li>\n  <li>358607726380311</li>\n</ol>\n\n<br/>\n<ol>\n  <li>Ships From</li>\n  <li>United States</li>\n</ol>\n\n<br/>\n<br/>\n\n<h6>Product Details</h6>\n<br/>\n<ul>\n  <li><p>The foam sockliner feels soft and comfortable</p></li>\n  <li><p>Pull tab</p></li>\n  <li><p>Not intended for use as Personal Protective Equipment</p></li>\n  <li><p>Colour Shown: White/Black/Oxygen Purple/Action Grape</p></li>\n  <li><p>Style: 921826-109</p></li>\n  <li><p>Country/Region of Origin: China</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Benefits</h6>\n<br/>\n<ul>\n  <li>\n    <p>Mesh and synthetic materials on the upper keep the fluid look of the OG while adding comfort</p>\n    and durability.\n  </li>\n  <li>\n    <p>Originally designed for performance running, the full-length Max Air unit adds soft, comfortable cushio</p>\n    ning underfoot.\n  </li>\n  <li><p>The foam midsole feels springy and soft.</p></li>\n  <li><p>The rubber outsole adds traction and durability.</p></li>\n</ul>\n\n<br/>\n<br/>\n\n<h6>Delivery and Returns</h6>\n<br/>\n<p>Your order of $200 or more gets free standard delivery.</p>\n<br/>\n<ul>\n  <li><p>Standard delivered 4-5 Business Days</p></li>\n  <li><p>Express delivered 2-4 Business Days</p></li>\n</ul>\n<br/>\n<p>Orders are processed and delivered Monday-Friday (excluding public holidays)</p>\n\n",
    newLabel: {
      enabled: false,
      content: "NEW",
    },
    sku: "WW75K5210YW/SV",
    createdAt: "2025-01-14T17:13:45.995Z",
    saleLabel: {
      enabled: false,
      content: "SALE",
    },
    name: "Nike Air Force 1 NDESTRUKT",
    price: 83.74,
    coverUrl:
      "https://api-dev-minimal-v510.vercel.app/assets/images/m_product/product_1.jpg",
    totalRatings: 4.2,
    totalSold: 763,
    totalReviews: 1947,
    subDescription:
      "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.",
    colors: ["#00AB55", "#000000", "#FFC0CB", "#FF4500", "#0000FF"],
  },
];

export default products;
