const productsData = [
  {
    id: "7b5f23e9-d4fc-4a89-8d69-61a8f39e72d2",
    gender: ["Men", "Woman"],
    category: ["Lab Coats"],
    collection: "Healthcare",
    sizes: ["Long", "Short"],
    images: [
      "/products/healthcare/labcoat_1.png",
      "/products/healthcare/labcoat_2.png",
    ],
    options: [
      {
        type: "pockets",
        variants: ["Pocket", "No Pocket"],
      },
      {
        type: "buttons",
        variants: ["Button", "Zipper"],
      },
    ],
    tags: [
      "Lab Coats",
      "Professional Wear",
      "Lightweight",
      "Breathable",
      "Durable",
      "Medical Uniform",
    ],
    description:
      "Experience superior comfort and professionalism with our lab coats. Designed for healthcare professionals, these lab coats are lightweight, breathable, and made with durable fabric to endure long workdays.",
    name: "Lab Coats",
    coverUrl: "/products/healthcare/labcoat_2.png",
    subDescription: "Professional lab coats for healthcare environments.",
    colors: ["#FFFFFF", "#2196F3", "#00BCD4"],
    newLabel: { enabled: false, content: "" },
    saleLabel: { enabled: false, content: "" },
  },
  {
    id: "7b5f23e9-d4fc-4a89-8d69-61a8f39e72d3",
    gender: ["Men", "Woman"],
    category: ["Caps"],
    collection: "Healthcare",
    sizes: ["One Size"],
    images: ["/products/healthcare/floral_cap.png"],
    tags: [
      "Nursing Caps",
      "Headwear",
      "Comfort",
      "Hygiene",
      "Medical Accessories",
      "Breathable",
    ],
    description:
      "Stay comfortable and hygienic with our nursing caps. These caps are perfect for healthcare professionals, featuring breathable materials and adjustable designs for all-day wear.",
    name: "Nursing Caps Patterned",
    coverUrl: "/products/healthcare/floral_cap.png",
    subDescription:
      "Hygienic and comfortable nursing caps designed for healthcare professionals.",
    message: "Any pattern can be added to the cap",
    // colors: ["#FFFFFF", "#2196F3", "#008000"],
    newLabel: { enabled: false, content: "" },
    saleLabel: { enabled: false, content: "" },
  },
  {
    id: "7b5f23e9-d4fc-4a89-8d69-61a8f39e72d9",
    gender: ["Men", "Woman"],
    category: ["Caps"],
    collection: "Healthcare",
    sizes: ["One Size"],
    images: ["/products/healthcare/clean_cap.png"],
    tags: [
      "Nursing Caps",
      "Headwear",
      "Comfort",
      "Hygiene",
      "Medical Accessories",
      "Breathable",
    ],
    description:
      "Stay comfortable and hygienic with our nursing caps. These caps are perfect for healthcare professionals, featuring breathable materials and adjustable designs for all-day wear.",
    name: "Nursing Caps Plain",
    coverUrl: "/products/healthcare/clean_cap.png",
    subDescription:
      "Hygienic and comfortable nursing caps designed for healthcare professionals.",
    colors: ["#FFFFFF", "#2196F3", "#008000", "#00BCD4"],
    newLabel: { enabled: false, content: "" },
    saleLabel: { enabled: false, content: "" },
  },
  {
    id: "7b5f23e9-d4fc-4a89-8d69-61a8f39e7223",
    gender: ["Men", "Woman"],
    category: ["Caps"],
    collection: "Healthcare",
    sizes: ["One Size"],
    images: ["/products/healthcare/surgical_gown.jpeg"],
    tags: [
      "Nursing Caps",
      "Headwear",
      "Comfort",
      "Hygiene",
      "Medical Accessories",
      "Breathable",
    ],
    description:
      "Stay comfortable and hygienic with our nursing caps. These caps are perfect for healthcare professionals, featuring breathable materials and adjustable designs for all-day wear.",
    name: "Surgical Gown",
    coverUrl: "/products/healthcare/surgical_gown.jpeg",
    subDescription:
      "Hygienic and comfortable nursing caps designed for healthcare professionals.",
    colors: ["#FFFFFF", "#2196F3", "#008000", "#00BCD4"],
    newLabel: { enabled: false, content: "" },
    saleLabel: { enabled: false, content: "" },
  },
  {
    id: "7b5f23e9-d4fc-4a89-8d69-61a8f39e7212",
    gender: ["Men", "Woman"],
    category: ["Caps"],
    collection: "Healthcare",
    sizes: ["One Size"],
    images: ["/products/healthcare/patient_gowns.jpeg"],
    tags: [
      "Nursing Caps",
      "Headwear",
      "Comfort",
      "Hygiene",
      "Medical Accessories",
      "Breathable",
    ],
    description:
      "Stay comfortable and hygienic with our nursing caps. These caps are perfect for healthcare professionals, featuring breathable materials and adjustable designs for all-day wear.",
    name: "Patient Gowns",
    coverUrl: "/products/healthcare/patient_gowns.jpeg",
    subDescription:
      "Hygienic and comfortable nursing caps designed for healthcare professionals.",
    colors: ["#FFFFFF", "#2196F3", "#008000", "#00BCD4"],
    newLabel: { enabled: false, content: "" },
    saleLabel: { enabled: false, content: "" },
  },
  {
    id: "7b5f23e9-d4fc-4a89-8d69-61a8f39e72d5",
    gender: ["Men", "Woman"],
    category: ["Scrubs"],
    collection: "Healthcare",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/products/healthcare/scrubs1.png",
      "/products/healthcare/scrubs2.png",
      "/products/healthcare/scrubs3.png",
      "/products/healthcare/scrubs4.png",
      "/products/healthcare/scrubs6.png",
      "/products/healthcare/scrubs7.png",
      "/products/healthcare/scrubs8.png",
      "/products/healthcare/scrubs9.png",
      "/products/healthcare/scrubs11.png",
      "/products/healthcare/scrubs12.png",
    ],
    tags: [
      "Scrubs",
      "Medical Uniform",
      "Lightweight",
      "Breathable",
      "Durable",
      "Professional Wear",
      "Comfort",
    ],
    description:
      "Our scrubs combine functionality and comfort, making them ideal for healthcare professionals. Crafted from a soft cotton-polyester blend, they are lightweight, breathable, and designed to keep you comfortable during long shifts.",
    name: "Scrubs",
    coverUrl: "/products/healthcare/scrubs1.png",
    subDescription: "Durable and comfortable scrubs for medical staff.",
    colors: ["#FFFFFF", "#000000", "#008000"],
    newLabel: { enabled: false, content: "" },
    saleLabel: { enabled: false, content: "" },
  },
];

export default productsData;
